// This file is generated automatically by Next.js
// Do not edit this file manually

type AppRoutes = "/" | "/app" | "/app/lectures/[id]" | "/app/new" | "/app/settings" | "/app/support" | "/app/support/[slug]" | "/auth/error" | "/auth/login"
type AppRouteHandlerRoutes = "/api/flashcards/[id]/progress" | "/api/inngest" | "/api/lectures" | "/api/lectures/[id]" | "/api/lectures/[id]/chat" | "/api/lectures/[id]/finalize" | "/api/lectures/[id]/pdf" | "/api/lectures/[id]/retry" | "/api/lectures/[id]/study" | "/api/lectures/[id]/study/regenerate" | "/api/lectures/link" | "/api/lectures/pdf" | "/api/lectures/text" | "/auth/callback" | "/auth/google" | "/auth/logout"
type PageRoutes = never
type LayoutRoutes = "/" | "/app"
type RedirectRoutes = never
type RewriteRoutes = never
type Routes = AppRoutes | PageRoutes | LayoutRoutes | RedirectRoutes | RewriteRoutes | AppRouteHandlerRoutes


interface ParamMap {
  "/": {}
  "/api/flashcards/[id]/progress": { "id": string; }
  "/api/inngest": {}
  "/api/lectures": {}
  "/api/lectures/[id]": { "id": string; }
  "/api/lectures/[id]/chat": { "id": string; }
  "/api/lectures/[id]/finalize": { "id": string; }
  "/api/lectures/[id]/pdf": { "id": string; }
  "/api/lectures/[id]/retry": { "id": string; }
  "/api/lectures/[id]/study": { "id": string; }
  "/api/lectures/[id]/study/regenerate": { "id": string; }
  "/api/lectures/link": {}
  "/api/lectures/pdf": {}
  "/api/lectures/text": {}
  "/app": {}
  "/app/lectures/[id]": { "id": string; }
  "/app/new": {}
  "/app/settings": {}
  "/app/support": {}
  "/app/support/[slug]": { "slug": string; }
  "/auth/callback": {}
  "/auth/error": {}
  "/auth/google": {}
  "/auth/login": {}
  "/auth/logout": {}
}


export type ParamsOf<Route extends Routes> = ParamMap[Route]

interface LayoutSlotMap {
  "/": never
  "/app": never
}


export type { AppRoutes, PageRoutes, LayoutRoutes, RedirectRoutes, RewriteRoutes, ParamMap, AppRouteHandlerRoutes }

declare global {
  /**
   * Props for Next.js App Router page components
   * @example
   * ```tsx
   * export default function Page(props: PageProps<'/blog/[slug]'>) {
   *   const { slug } = await props.params
   *   return <div>Blog post: {slug}</div>
   * }
   * ```
   */
  interface PageProps<AppRoute extends AppRoutes> {
    params: Promise<ParamMap[AppRoute]>
    searchParams: Promise<Record<string, string | string[] | undefined>>
  }

  /**
   * Props for Next.js App Router layout components
   * @example
   * ```tsx
   * export default function Layout(props: LayoutProps<'/dashboard'>) {
   *   return <div>{props.children}</div>
   * }
   * ```
   */
  type LayoutProps<LayoutRoute extends LayoutRoutes> = {
    params: Promise<ParamMap[LayoutRoute]>
    children: React.ReactNode
  } & {
    [K in LayoutSlotMap[LayoutRoute]]: React.ReactNode
  }

  /**
   * Context for Next.js App Router route handlers
   * @example
   * ```tsx
   * export async function GET(request: NextRequest, context: RouteContext<'/api/users/[id]'>) {
   *   const { id } = await context.params
   *   return Response.json({ id })
   * }
   * ```
   */
  interface RouteContext<AppRouteHandlerRoute extends AppRouteHandlerRoutes> {
    params: Promise<ParamMap[AppRouteHandlerRoute]>
  }
}
