// This file is generated automatically by Next.js
// Do not edit this file manually
// This file validates that all pages and layouts export the correct types

import type { AppRoutes, LayoutRoutes, ParamMap, AppRouteHandlerRoutes } from "./routes.js"
import type { ResolvingMetadata, ResolvingViewport } from "next/types.js"
import type { NextRequest } from 'next/server.js'

type AppPageConfig<Route extends AppRoutes = AppRoutes> = {
  default: React.ComponentType<{ params: Promise<ParamMap[Route]> } & any> | ((props: { params: Promise<ParamMap[Route]> } & any) => React.ReactNode | Promise<React.ReactNode> | never | void | Promise<void>)
  generateStaticParams?: (props: { params: ParamMap[Route] }) => Promise<any[]> | any[]
  generateMetadata?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingMetadata
  ) => Promise<any> | any
  generateViewport?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingViewport
  ) => Promise<any> | any
  metadata?: any
  viewport?: any
}

type LayoutConfig<Route extends LayoutRoutes = LayoutRoutes> = {
  default: React.ComponentType<LayoutProps<Route>> | ((props: LayoutProps<Route>) => React.ReactNode | Promise<React.ReactNode> | never | void | Promise<void>)
  generateStaticParams?: (props: { params: ParamMap[Route] }) => Promise<any[]> | any[]
  generateMetadata?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingMetadata
  ) => Promise<any> | any
  generateViewport?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingViewport
  ) => Promise<any> | any
  metadata?: any
  viewport?: any
}

type RouteHandlerConfig<Route extends AppRouteHandlerRoutes = AppRouteHandlerRoutes> = {
  GET?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  POST?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  PUT?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  PATCH?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  DELETE?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  HEAD?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  OPTIONS?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
}


// Validate ../../../src/app/app/lectures/[id]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/app/lectures/[id]">> = Specific
  const handler = {} as typeof import("../../../src/app/app/lectures/[id]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/app/new/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/app/new">> = Specific
  const handler = {} as typeof import("../../../src/app/app/new/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/app/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/app">> = Specific
  const handler = {} as typeof import("../../../src/app/app/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/app/settings/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/app/settings">> = Specific
  const handler = {} as typeof import("../../../src/app/app/settings/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/app/support/[slug]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/app/support/[slug]">> = Specific
  const handler = {} as typeof import("../../../src/app/app/support/[slug]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/app/support/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/app/support">> = Specific
  const handler = {} as typeof import("../../../src/app/app/support/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/auth/error/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/auth/error">> = Specific
  const handler = {} as typeof import("../../../src/app/auth/error/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/auth/login/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/auth/login">> = Specific
  const handler = {} as typeof import("../../../src/app/auth/login/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/">> = Specific
  const handler = {} as typeof import("../../../src/app/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/flashcards/[id]/progress/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/flashcards/[id]/progress">> = Specific
  const handler = {} as typeof import("../../../src/app/api/flashcards/[id]/progress/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/inngest/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/inngest">> = Specific
  const handler = {} as typeof import("../../../src/app/api/inngest/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/lectures/[id]/chat/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/lectures/[id]/chat">> = Specific
  const handler = {} as typeof import("../../../src/app/api/lectures/[id]/chat/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/lectures/[id]/finalize/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/lectures/[id]/finalize">> = Specific
  const handler = {} as typeof import("../../../src/app/api/lectures/[id]/finalize/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/lectures/[id]/pdf/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/lectures/[id]/pdf">> = Specific
  const handler = {} as typeof import("../../../src/app/api/lectures/[id]/pdf/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/lectures/[id]/retry/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/lectures/[id]/retry">> = Specific
  const handler = {} as typeof import("../../../src/app/api/lectures/[id]/retry/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/lectures/[id]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/lectures/[id]">> = Specific
  const handler = {} as typeof import("../../../src/app/api/lectures/[id]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/lectures/[id]/study/regenerate/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/lectures/[id]/study/regenerate">> = Specific
  const handler = {} as typeof import("../../../src/app/api/lectures/[id]/study/regenerate/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/lectures/[id]/study/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/lectures/[id]/study">> = Specific
  const handler = {} as typeof import("../../../src/app/api/lectures/[id]/study/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/lectures/link/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/lectures/link">> = Specific
  const handler = {} as typeof import("../../../src/app/api/lectures/link/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/lectures/pdf/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/lectures/pdf">> = Specific
  const handler = {} as typeof import("../../../src/app/api/lectures/pdf/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/lectures/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/lectures">> = Specific
  const handler = {} as typeof import("../../../src/app/api/lectures/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/lectures/text/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/lectures/text">> = Specific
  const handler = {} as typeof import("../../../src/app/api/lectures/text/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/auth/callback/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/auth/callback">> = Specific
  const handler = {} as typeof import("../../../src/app/auth/callback/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/auth/google/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/auth/google">> = Specific
  const handler = {} as typeof import("../../../src/app/auth/google/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/auth/logout/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/auth/logout">> = Specific
  const handler = {} as typeof import("../../../src/app/auth/logout/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}





// Validate ../../../src/app/app/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/app">> = Specific
  const handler = {} as typeof import("../../../src/app/app/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/">> = Specific
  const handler = {} as typeof import("../../../src/app/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}
